### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Dunstrikex** [shekohex/coemu#7]
`sqlx migrate run --database-url 'sqlite://data/coemu.db?mode=rwc'`

CMD>
error: while resolving migrations: The system cannot find the file specified. (os error 2)

**Comment by shekohex** [comment]
maybe try `sqlx migrate run --soruce ./migrations --database-url 'sqlite://data/coemu.db'`

**Comment by Mlzu** [comment]
use `cargo sqlx migrate run --database-url 'sqlite://data/coemu.db?mode=rwc'`

**Comment by shekohex** [comment]
Closing as solved.
